@startuml
skinparam packageStyle rectangle
skinparam linetype polyline
package User_Interface {


	package User_session #DDDDFF {
		map Create_user {
		}
		map Login_or_Logout{
		}
		map Create_channel{
		}
		map Join_channel{
		}
		map Send_or_Read_msg{
		}
	}
	object UI {

		}
	package Encryption #DDDFAF{
		map Encrypt {

		}
		map Decrypt {

		}
	}
	map UI_connection {

	}	
}

package Server {
	map Create_user_entry {
	}
	map Validate_Login{
	}
	object User_db{
	}
	map Create_channel_entry	{
	}
	map Associate_users{
	}
	map Store_enc_msg{
	}
	map Forward_Log{
	}
	object Channel_db{
	}
	object Encrypted_Log{
	}
	map Server_connection {
	}

}
Create_user -[hidden]down- Login_or_Logout
Login_or_Logout -[hidden]down- Create_channel
Create_channel -[hidden]down- Join_channel
Join_channel -[hidden]down- Send_or_Read_msg

Decrypt -[hidden]down- Encrypt

Create_user -[hidden]left- UI
User_session -- UI

UI -- Encryption
Decrypt -[hidden]left- UI_connection
Encryption -- UI_connection
@enduml